// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ssentinull/kumparan-article-service/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// ArticleRepository is an autogenerated mock type for the ArticleRepository type
type ArticleRepository struct {
	mock.Mock
}

// CalculateVectors provides a mock function with given fields: _a0, _a1
func (_m *ArticleRepository) CalculateVectors(_a0 context.Context, _a1 *model.Article) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Article) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *ArticleRepository) Create(_a0 context.Context, _a1 *model.Article) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Article) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: _a0, _a1
func (_m *ArticleRepository) Read(_a0 context.Context, _a1 model.QueryBuilder) ([]model.Article, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []model.Article
	if rf, ok := ret.Get(0).(func(context.Context, model.QueryBuilder) []model.Article); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.QueryBuilder) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
